### PR TITLE
Migrate project to Truffle v4.0

### PR DESCRIPTION
**Pull request by jksf**
https://github.com/trufflesuite/truffle/releases/tag/v4.0.0

Changes:
- uses built-in `testrpc` for tests
- uses `truffle-config.js` file with empty configuration (to use builtin testrpc env)
- updates solc compiler (needed changes in contracts to silence warnings)

### CODE REVIEW

**Comment by biern** [comment]
👍 I'm not 100% sure about removal of testrpc yet. We will need a seed mechanism and possibly an auto-migration for easier development with the frontend. Can we do that with `testrpc` boundled with truffle?

**Comment by jksf** [comment]
We should be able to use `truffle develop` mode instead of `testrpc`, but it turns out it is unusable with MetaMask. I'm not sure if it is a Truffle bug or it is not meant to be used this way. Hardcoded mnemonic in `truffle develop` is considered invalid by MetaMask. 
Therefore, I restored `testrpc` in the project and also improved npm scripts a bit.

**Comment by biern** [comment]
Looks good, I've noticed one additional issue though. Codeship doesn't seem to support running builds for PRs from forked repos - https://community.codeship.com/t/github-prs-from-forked-repositories-dont-get-built/55
The simplest workaround for us is probably to work with project repo directly, unless you can find something out.

**Comment by jksf** [comment]
I run the CI by pushing the branch to the upstream, and it passed. I will reconsider working directly on the organization repositories in the future.

**Pull request merged**
