### PR TITLE
Update Truffle and TestRPC dependencies

### PR DESCRIPTION
**Pull request by jksf**
- Update Truffle and TestRPC dependencies
- Do not autoformat `package.json` (conflicts with `npm install` formatting)
- Remove unused dependency to `yargs`

### CODE REVIEW

**Comment by jksf** [comment]
Truffle 4.0.1 fixes several important issues: https://github.com/trufflesuite/truffle/releases/tag/v4.0.1

**Comment by jksf** [comment]
Local build works ok, but CodeShip has a bad day.
```
2017-11-08T18:55:43.939Znpm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

@biern Can you check clean `npm install` from your computer?

**Comment by jksf** [comment]
Ok, CodeShip got his shit together and finally passed.

**Comment by biern** [comment]
👍  Looks like one of the biggest updates in truffle is a new, cooler seed phrase.

**Pull request merged**
